### ISSUE TITLE
hotelReservation | 'docker compose up -d' failing to build

### ISSUE THREAD

**Issue by elibakshi** [delimitrou/DeathStarBench#320] opened 2024-01-16 01:01 UTC
Hello!

I recently pulled the latest updates for hotelReservation and I am now having issues getting it to run.

When using docker compose, I am getting this error: 

> Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "reservation": executable file not found in $PATH: unknown

<img width="1075" alt="Screenshot 2024-01-15 at 4 49 49 PM" src="https://github.com/delimitrou/DeathStarBench/assets/25834936/5317dcef-58b0-4289-a240-f52b19838754">

--------

Also, in order to get the Google Maps API to load correctly do I just need to provide a personal key at /services/frontend/static/index.html in this line?: `<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&callback=initMap" async defer></script>`

I would really appreciate any input on this. Thanks so much!

**Comment by Red-GV** [comment] 2024-01-16 14:24
Heya @elibakshi, can you try doing `./reservation` as the entrypoint for the reservation node?

**Comment by elibakshi** [comment] 2024-01-17 00:17
Hello @Red-GV, fixing the entrypoints that were erroring worked like a charm. Thanks for your help!

**Comment by StreamAzure** [comment] 2024-01-17 09:36
> Heya @elibakshi, can you try doing `./reservation` as the entrypoint for the reservation node?

thanks for your fix! It totally saved the day for me

**Comment by elibakshi** [comment] 2024-01-19 02:14
Hello again, @Red-GV !

So prefixing all of the entrypoints with "./" fixed my issue initially. But after re-building, I ran into another issue that is (maybe?) related:

![Screenshot 2024-01-18 at 6 08 20 PM](https://github.com/delimitrou/DeathStarBench/assets/25834936/44f9a1a1-89be-4f02-a287-d913f2dfe6b7)

From this output it seems that the frontend container can't find the config.json file, and thus never exposes port 5000. Would there need to be a line added to the Dockerfile to COPY it over to the directories of the new entrypoints?

Once again, really appreciate your time and help!

**Comment by Red-GV** [comment] 2024-01-19 14:15
Heya @elibakshi, I think it can be done without needing to modify the Dockerfile by modifying the `compose` file. Haven't tried it as of yet, but this might work (e309d93a95314fcd17d6884c9edfd41d277e2c31):

```
configs:
      server_config:
        file: ./config.json
        name: config.json
```

**Comment by elibakshi** [comment] 2024-01-19 21:59
Thanks for the suggestion, @Red-GV. I am not too sure if it's an issue just on my end, but that still didn't fix.

The only way I can get somewhere is if I add `COPY config.json config.json` (as /workspace) and `COPY --from=builder /workspace/config.json .` (as /) in the Dockerfile.

At first look at the logs for the frontend container it seems that it can now find the ./config.json and all is well:

![Screenshot 2024-01-19 at 1 58 10 PM](https://github.com/delimitrou/DeathStarBench/assets/25834936/3ab68552-4e4a-4686-b3f7-d18df8e9a71a)

However, when attempting to actually connect to the website via. browser, I only get a `404 page Not Found` response.

**Comment by Red-GV** [comment] 2024-01-22 00:39
Hmm, alright. I'll try to play with it and see if I come up with a solution that doesn't involve copying that file into the Dockerfile (I'd be kinda surprised if there wasn't a way to modify that). The reason why I'm not completely all for the "copy into Dockerfile" approach is because in the `helm` chart deployments, the files are placed in with that deployment style. So I don't see why the file needs to be in there twice so to speak.

The browser issue should be fixed by this guy: https://github.com/delimitrou/DeathStarBench/pull/319

The api does work so you can use the `wrk2` client in order to talk to the services via the that.

**Comment by Red-GV** [comment] 2024-01-23 21:29
Heya @elibakshi, 

I've confirmed on my end that the PR I highlighted last time will solve the `404` issue when you load it from the browser or fire a `curl` requests against the `frontend` service. I also think that this change (27f637de6d60198bfcc5c0c35d63d4cdb9d55d44) for the `docker-compose.yml` should fix things. Doesn't fully play around with `podman`, but I think it should work fine with the `docker` cli. Maybe you could give it a spin?

**Comment by tuannv1104** [comment] 2024-03-25 08:44
Hi @Red-GV 

I've tested the hotel reservation service code, and it seems that the frontend only consists of a basic UI displaying a Google map with some pins. Is this the entirety of the UI for the hotel reservation service?

**Closed** 2024-04-09 17:03 UTC

**Comment by Red-GV** [comment] 2024-05-31 13:21
Heya @elibakshi ,

My suspicions is that there was a conflict between PRs that was not properly resolved. There appeared to have been some back and forth which removed some of the changes I had made in one of the refactors. This resulted in even more issues. I think one of the current PRs should fix the issue once that gets merged. However, I'm not a maintainer of the codebase though, so I don't know when that merge will occur.
